### ISSUE TITLE
Hey, just noticed you used an old commit!

### ISSUE THREAD

**Issue by aunali1** [rahulkalpsts107/raunix#1]
Hi,

I saw that you used my code but its been a while since I updated it. After clearing up some schoolwork, I got back on the project last week and made lots of changes, including restructuring of the build system, panic handlers, and an 'experimental' kernel library interface. If you need help, just ask!

Oh, and If you want the 'bleeding-edge' code you should visit my personal repository at https://git.aunali1.com/.

Personally, I suggest forking my repository first and then create a separate branch in which you can put all your changes.

Sincerely,
Aun-Ali Zaidi

printf("The first release of BasicOS is going to be in 2 months.\n");

**Comment by rahulkalpsts107** [comment]
Hi ,

Thanks for the information .
I have used your source to bring up an UNIX like OS with bare features from MINIX. 
Since I have a different aim here to make it like UNIX , I had created a new repo.
I Could fork your project and work on it but if that's the case , I need to understand a bit of what's going on in GDT and Paging.
If you could explain or blog about it , I can contribute to your documentation and soon work on it

Cheers,
Rahul

**Comment by aunali1** [comment]
Hey,

First off, I think we should communicate through email instead of through the Issues. My email is admin@kodeit.net.

Second, my primary intent was to write a microkernel simillar to MINIX (I have the original "Operating Systems: Design and Implementation" written by Andrew S. Tannebaum, the creator of MINIX from 1987!), but the current sources have evolved into a monolithickernel like Linux, with a planned lodable module design.

Third, the focus of this kernel was full POSIX compliance, unlike Linux which is mostly POSIX compliant. 

Fourth, like I said previoulsy, I had lots of schoolwork, (AP in high school is hardcore!) so I couldn't get much done, but know I have time to work on it here is what I have planned/been currently working on:
- Multi-Arch: x86, x86_64, ARMv7
- Multiple Filesystems: TmpFS, ProcFs, EXT2, EXT3, EXT4, FAT, FAT32, NTFS, BTRFS, HFS
- User-mode support
- Block Device support (like '/dev/...' etc.)
- Linux Driver compatibilty (Saves a LOT of time writing drivers!) (GNU Mach has its own implementation.)
- Become a complete Microkernel
- Package management system (More like Debian's 'apt-get' instead of RHEL's 'yum'.)I have dedicated servers for hosting!)
- Open Source GUI (GNOME, KDE, LXDE, XFCE, etc.)
- anything else you can think of ...

Lastly, I can explain how the paging and GDT work. I'm working on a blog post right now to explain all the info. You can visit my blog at https://blog.aunali1.com.

So, I really think we can contribute to each others projects, but we also need to set some fine lines when it comes to Licensing.

Sincerely,
Aun-Ali Zaidi
